### ISSUE TITLE
Could you specify the version of Numpy and Tensorflow used

### ISSUE THREAD

**Issue by AiliAili** [jmhessel/multi-retrieval#6]
Hi there,

Thank you for sharing your code.
I am wondering which version of numpy and tensorflow you are using.
I encountered errors in running your train_doc.py, using numpy=1.20.1 and tf=2.1.0.
If I use a numpy <1.20, then the "from lapjv import lapjv" will throw out exceptions.
If I use numpy >=1.20, this exception disappears but it seems have an incompatibility with Tensorflow. It will throw out 

> NotImplementedError: Cannot convert a symbolic Tensor (time_distributed_1/gru/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

Googled around, found out it's about the compatibility of numpy and tensorflow.

Could you please specify which version we should use?
Have been stuck with this issue for a couple of days.

Thank you for your time.

**Comment by jmhessel** [comment]
Hi!

Thanks for your interest in the code and giving it a try. I agree, this error arises from a mismatch between the numpy and tensorflow versions. Can you try downgrading lapjv? They recently bumped their requirements to the very newest numpy just last month. I.e., can you try uninstalling numpy, reinstalling tensorflow 2.1 (which will install a compatable version of numpy) and then getting `lapjv == 1.3.1` or one of the ones before feb. 2021 here https://github.com/src-d/lapjv/tags ?

Jack

**Comment by AiliAili** [comment]
Hi Jack,

Thank you very much for your timely reply. It works to install an earlier version.
For the convenience of others, I did the following:
(1) get the earlier version of their source code
(2) run `python3 setup.py install`
PS. pip3 install lapjv == 1.3.1 didn't work on my end.

Cheers,

**Comment by jmhessel** [comment]
Thanks for this @AiliAili !! Can you let me know which version of lapjv ended up working, so I can update requirements.txt? I think this can be gotten via `import lapjv; print(lapjv.__version__)` or similar.

**Comment by AiliAili** [comment]
I used the version of 1.3.1. 
I think any version before 1.3.2 will be fine (they upgraded to numpy 1.20 since 1.3.2).
In a word, it's the incompatibility of numpy=1.20 and tf, leading to such an issue. This issue may be solved in the future.
